export * from './calendarConfController.service';
import { CalendarConfControllerService } from './calendarConfController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './summerOfLoveController.service';
import { SummerOfLoveControllerService } from './summerOfLoveController.service';
export * from './sushiController.service';
import { SushiControllerService } from './sushiController.service';
export * from './wineController.service';
import { WineControllerService } from './wineController.service';
export const APIS = [CalendarConfControllerService, ProductControllerService, SummerOfLoveControllerService, SushiControllerService, WineControllerService];
