/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';
import {Observable} from "rxjs";

import { Sushi } from '../model/sushi';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({providedIn: 'root'})
export class SushiControllerService {

    protected basePath = 'https://servicedbacorp741w.com:8444/santannaservice';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * delete
     *
     * @param sushiId
     * @param name
     * @param ingredients
     * @param category
     * @param subCategory
     * @param price
     * @param available
     * @param takeAwayProduct
     * @param takeAwayPrice
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUsingDELETE3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteUsingDELETE3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteUsingDELETE3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteUsingDELETE3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sushiId !== undefined && sushiId !== null) {
            queryParameters = queryParameters.set('sushiId', <any>sushiId);
        }
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (ingredients !== undefined && ingredients !== null) {
            queryParameters = queryParameters.set('ingredients', <any>ingredients);
        }
        if (category !== undefined && category !== null) {
            queryParameters = queryParameters.set('category', <any>category);
        }
        if (subCategory !== undefined && subCategory !== null) {
            queryParameters = queryParameters.set('subCategory', <any>subCategory);
        }
        if (price !== undefined && price !== null) {
            queryParameters = queryParameters.set('price', <any>price);
        }
        if (available !== undefined && available !== null) {
            queryParameters = queryParameters.set('available', <any>available);
        }
        if (takeAwayProduct !== undefined && takeAwayProduct !== null) {
            queryParameters = queryParameters.set('takeAwayProduct', <any>takeAwayProduct);
        }
        if (takeAwayPrice !== undefined && takeAwayPrice !== null) {
            queryParameters = queryParameters.set('takeAwayPrice', <any>takeAwayPrice);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/v1/sushi/delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * retrieveAll
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public retrieveAllUsingGET2(observe?: 'body', reportProgress?: boolean): Observable<Array<Sushi>>;
    public retrieveAllUsingGET2(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Sushi>>>;
    public retrieveAllUsingGET2(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Sushi>>>;
    public retrieveAllUsingGET2(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Sushi>>(`${this.basePath}/api/v1/sushi/findall`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * save
     *
     * @param sushiId
     * @param name
     * @param ingredients
     * @param category
     * @param subCategory
     * @param price
     * @param available
     * @param takeAwayProduct
     * @param takeAwayPrice
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveUsingPOST3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public saveUsingPOST3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public saveUsingPOST3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public saveUsingPOST3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sushiId !== undefined && sushiId !== null) {
            queryParameters = queryParameters.set('sushiId', <any>sushiId);
        }
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (ingredients !== undefined && ingredients !== null) {
            queryParameters = queryParameters.set('ingredients', <any>ingredients);
        }
        if (category !== undefined && category !== null) {
            queryParameters = queryParameters.set('category', <any>category);
        }
        if (subCategory !== undefined && subCategory !== null) {
            queryParameters = queryParameters.set('subCategory', <any>subCategory);
        }
        if (price !== undefined && price !== null) {
            queryParameters = queryParameters.set('price', <any>price);
        }
        if (available !== undefined && available !== null) {
            queryParameters = queryParameters.set('available', <any>available);
        }
        if (takeAwayProduct !== undefined && takeAwayProduct !== null) {
            queryParameters = queryParameters.set('takeAwayProduct', <any>takeAwayProduct);
        }
        if (takeAwayPrice !== undefined && takeAwayPrice !== null) {
            queryParameters = queryParameters.set('takeAwayPrice', <any>takeAwayPrice);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/api/v1/sushi/save`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     *
     * @param sushiId
     * @param name
     * @param ingredients
     * @param category
     * @param subCategory
     * @param price
     * @param available
     * @param takeAwayProduct
     * @param takeAwayPrice
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateUsingPUT3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateUsingPUT3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateUsingPUT3(sushiId?: number, name?: string, ingredients?: string, category?: 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE', subCategory?: string, price?: number, available?: boolean, takeAwayProduct?: boolean, takeAwayPrice?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sushiId !== undefined && sushiId !== null) {
            queryParameters = queryParameters.set('sushiId', <any>sushiId);
        }
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (ingredients !== undefined && ingredients !== null) {
            queryParameters = queryParameters.set('ingredients', <any>ingredients);
        }
        if (category !== undefined && category !== null) {
            queryParameters = queryParameters.set('category', <any>category);
        }
        if (subCategory !== undefined && subCategory !== null) {
            queryParameters = queryParameters.set('subCategory', <any>subCategory);
        }
        if (price !== undefined && price !== null) {
            queryParameters = queryParameters.set('price', <any>price);
        }
        if (available !== undefined && available !== null) {
            queryParameters = queryParameters.set('available', <any>available);
        }
        if (takeAwayProduct !== undefined && takeAwayProduct !== null) {
            queryParameters = queryParameters.set('takeAwayProduct', <any>takeAwayProduct);
        }
        if (takeAwayPrice !== undefined && takeAwayPrice !== null) {
            queryParameters = queryParameters.set('takeAwayPrice', <any>takeAwayPrice);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.put<any>(`${this.basePath}/api/v1/sushi/update`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
