/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EventBooking { 
    accomodation?: string;
    arrived?: boolean;
    code?: string;
    confirmed?: boolean;
    email?: string;
    eventBookingId?: number;
    guests?: number;
    name?: string;
    note?: string;
    phone?: string;
    pr?: string;
    prefix?: string;
    reservationDate?: string;
    typeAccomodation?: number;
}
