/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Sushi { 
    available?: boolean;
    category?: Sushi.CategoryEnum;
    ingredients?: string;
    name?: string;
    price?: number;
    subCategory?: string;
    sushiId?: number;
    takeAwayPrice?: number;
    takeAwayProduct?: boolean;
}
export namespace Sushi {
    export type CategoryEnum = 'TARTARESASHIMICARPACCIO' | 'HOSOMAKITEMAKI' | 'ROLLS8PZ' | 'SUSHIGIO2PZ' | 'SPECIALS' | 'SUSHIDEFAULT' | 'NIGIRI1PZ' | 'SUSHISPECIALETONNO' | 'SUSHISPECIALERICCIOLA' | 'SUSHISPECIALE';
    export const CategoryEnum = {
        TARTARESASHIMICARPACCIO: 'TARTARESASHIMICARPACCIO' as CategoryEnum,
        HOSOMAKITEMAKI: 'HOSOMAKITEMAKI' as CategoryEnum,
        ROLLS8PZ: 'ROLLS8PZ' as CategoryEnum,
        SUSHIGIO2PZ: 'SUSHIGIO2PZ' as CategoryEnum,
        SPECIALS: 'SPECIALS' as CategoryEnum,
        SUSHIDEFAULT: 'SUSHIDEFAULT' as CategoryEnum,
        NIGIRI1PZ: 'NIGIRI1PZ' as CategoryEnum,
        SUSHISPECIALETONNO: 'SUSHISPECIALETONNO' as CategoryEnum,
        SUSHISPECIALERICCIOLA: 'SUSHISPECIALERICCIOLA' as CategoryEnum,
        SUSHISPECIALE: 'SUSHISPECIALE' as CategoryEnum
    };
}
