/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Wine { 
    available?: boolean;
    country?: string;
    gradation?: string;
    grapes?: string;
    name?: string;
    price?: number;
    producer?: string;
    region?: string;
    wineId?: number;
    wineType?: Wine.WineTypeEnum;
    year?: string;
}
export namespace Wine {
    export type WineTypeEnum = 'BIANCO' | 'ROSSO' | 'ROSATO' | 'BOLLICINE' | 'CHAMPAGNE';
    export const WineTypeEnum = {
        BIANCO: 'BIANCO' as WineTypeEnum,
        ROSSO: 'ROSSO' as WineTypeEnum,
        ROSATO: 'ROSATO' as WineTypeEnum,
        BOLLICINE: 'BOLLICINE' as WineTypeEnum,
        CHAMPAGNE: 'CHAMPAGNE' as WineTypeEnum
    };
}
